services:

  nodejs-server:
    image : sidhishkumar/chaicode:latest
    deploy:
      replicas: 2
    networks: 
      - chaicode-internal

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - chaicode-internal

networks:
  chaicode-internal:
    driver: bridge
  